### ISSUE TITLE
How to start the program?

### ISSUE THREAD

**Issue by ElPicador** [Zekii/interview#1]
I don't manage to start the program.

I have a working java/maven env but I get a weird error:

```bash
» mvn test                                                                                         
executing mvnw instead of mvn
/Users/rcs/Projects/algolia/interview
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

**Comment by Zekii** [comment]
Can you try to start the program with `mvnw spring-boot:run` ? Because it does work on my side with mvn test, but i always start my spring application with the mvnw exec.
Since the log file is too large, i add it with GIT LFS, do not forget to pull it too.

**Comment by Zekii** [comment]
Added the .mvn folder containing the wrapper. The folder was in the gitignore.
Should fix it.

**Comment by ElPicador** [comment]
I've pulled the latest version, and I still have the same issue.
Could you migrate the project to use the mvn of the system instead of the one included?

**Comment by Zekii** [comment]
Can you try it again with the last version, i forgot to track a file related to the wrapper.
Meanwhile i'll migrate the project :)

**Comment by Zekii** [comment]
Have you pull the log file ? git lfs pull

**Comment by ElPicador** [comment]
It was not written in the documentation to do it, I've done it. It works now. Thanks

**Comment by Zekii** [comment]
It explained how it works, but not how to make it work haha
